export type CountryOption = {
  code: string;
  name: string;
  dialCode: string;
};

export const countries: CountryOption[] = [
  { code: "DZ", name: "Algerie", dialCode: "+213" },
  { code: "DE", name: "Allemagne", dialCode: "+49" },
  { code: "AO", name: "Angola", dialCode: "+244" },
  { code: "SA", name: "Arabie saoudite", dialCode: "+966" },
  { code: "AR", name: "Argentine", dialCode: "+54" },
  { code: "AU", name: "Australie", dialCode: "+61" },
  { code: "AT", name: "Autriche", dialCode: "+43" },
  { code: "BE", name: "Belgique", dialCode: "+32" },
  { code: "BJ", name: "Benin", dialCode: "+229" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226" },
  { code: "BI", name: "Burundi", dialCode: "+257" },
  { code: "CM", name: "Cameroun", dialCode: "+237" },
  { code: "CA", name: "Canada", dialCode: "+1" },
  { code: "CV", name: "Cap-Vert", dialCode: "+238" },
  { code: "CF", name: "Centrafrique", dialCode: "+236" },
  { code: "TD", name: "Tchad", dialCode: "+235" },
  { code: "CL", name: "Chili", dialCode: "+56" },
  { code: "CN", name: "Chine", dialCode: "+86" },
  { code: "CY", name: "Chypre", dialCode: "+357" },
  { code: "CO", name: "Colombie", dialCode: "+57" },
  { code: "KM", name: "Comores", dialCode: "+269" },
  { code: "CG", name: "Congo", dialCode: "+242" },
  { code: "CD", name: "Congo RDC", dialCode: "+243" },
  { code: "CI", name: "Cote d'Ivoire", dialCode: "+225" },
  { code: "HR", name: "Croatie", dialCode: "+385" },
  { code: "DK", name: "Danemark", dialCode: "+45" },
  { code: "DJ", name: "Djibouti", dialCode: "+253" },
  { code: "EG", name: "Egypte", dialCode: "+20" },
  { code: "AE", name: "Emirats arabes unis", dialCode: "+971" },
  { code: "EC", name: "Equateur", dialCode: "+593" },
  { code: "ES", name: "Espagne", dialCode: "+34" },
  { code: "US", name: "Etats-Unis", dialCode: "+1" },
  { code: "EE", name: "Estonie", dialCode: "+372" },
  { code: "ET", name: "Ethiopie", dialCode: "+251" },
  { code: "FI", name: "Finlande", dialCode: "+358" },
  { code: "FR", name: "France", dialCode: "+33" },
  { code: "GA", name: "Gabon", dialCode: "+241" },
  { code: "GM", name: "Gambie", dialCode: "+220" },
  { code: "GH", name: "Ghana", dialCode: "+233" },
  { code: "GN", name: "Guinee", dialCode: "+224" },
  { code: "GQ", name: "Guinee equatoriale", dialCode: "+240" },
  { code: "GW", name: "Guinee-Bissau", dialCode: "+245" },
  { code: "GR", name: "Grece", dialCode: "+30" },
  { code: "HT", name: "Haiti", dialCode: "+509" },
  { code: "HU", name: "Hongrie", dialCode: "+36" },
  { code: "IN", name: "Inde", dialCode: "+91" },
  { code: "ID", name: "Indonesie", dialCode: "+62" },
  { code: "IE", name: "Irlande", dialCode: "+353" },
  { code: "IS", name: "Islande", dialCode: "+354" },
  { code: "IT", name: "Italie", dialCode: "+39" },
  { code: "JP", name: "Japon", dialCode: "+81" },
  { code: "JO", name: "Jordanie", dialCode: "+962" },
  { code: "KE", name: "Kenya", dialCode: "+254" },
  { code: "LB", name: "Liban", dialCode: "+961" },
  { code: "LR", name: "Liberia", dialCode: "+231" },
  { code: "LY", name: "Libye", dialCode: "+218" },
  { code: "LT", name: "Lituanie", dialCode: "+370" },
  { code: "LU", name: "Luxembourg", dialCode: "+352" },
  { code: "MG", name: "Madagascar", dialCode: "+261" },
  { code: "MY", name: "Malaisie", dialCode: "+60" },
  { code: "ML", name: "Mali", dialCode: "+223" },
  { code: "MT", name: "Malte", dialCode: "+356" },
  { code: "MA", name: "Maroc", dialCode: "+212" },
  { code: "MU", name: "Maurice", dialCode: "+230" },
  { code: "MR", name: "Mauritanie", dialCode: "+222" },
  { code: "MX", name: "Mexique", dialCode: "+52" },
  { code: "MC", name: "Monaco", dialCode: "+377" },
  { code: "MZ", name: "Mozambique", dialCode: "+258" },
  { code: "NA", name: "Namibie", dialCode: "+264" },
  { code: "NE", name: "Niger", dialCode: "+227" },
  { code: "NG", name: "Nigeria", dialCode: "+234" },
  { code: "NO", name: "Norvege", dialCode: "+47" },
  { code: "NZ", name: "Nouvelle-Zelande", dialCode: "+64" },
  { code: "UG", name: "Ouganda", dialCode: "+256" },
  { code: "NL", name: "Pays-Bas", dialCode: "+31" },
  { code: "PE", name: "Perou", dialCode: "+51" },
  { code: "PH", name: "Philippines", dialCode: "+63" },
  { code: "PL", name: "Pologne", dialCode: "+48" },
  { code: "PT", name: "Portugal", dialCode: "+351" },
  { code: "QA", name: "Qatar", dialCode: "+974" },
  { code: "CZ", name: "Republique tcheque", dialCode: "+420" },
  { code: "DO", name: "Republique dominicaine", dialCode: "+1" },
  { code: "RO", name: "Roumanie", dialCode: "+40" },
  { code: "GB", name: "Royaume-Uni", dialCode: "+44" },
  { code: "RW", name: "Rwanda", dialCode: "+250" },
  { code: "SN", name: "Senegal", dialCode: "+221" },
  { code: "RS", name: "Serbie", dialCode: "+381" },
  { code: "SL", name: "Sierra Leone", dialCode: "+232" },
  { code: "SG", name: "Singapour", dialCode: "+65" },
  { code: "SK", name: "Slovaquie", dialCode: "+421" },
  { code: "SI", name: "Slovenie", dialCode: "+386" },
  { code: "SO", name: "Somalie", dialCode: "+252" },
  { code: "ZA", name: "Afrique du Sud", dialCode: "+27" },
  { code: "KR", name: "Coree du Sud", dialCode: "+82" },
  { code: "LK", name: "Sri Lanka", dialCode: "+94" },
  { code: "SE", name: "Suede", dialCode: "+46" },
  { code: "CH", name: "Suisse", dialCode: "+41" },
  { code: "TZ", name: "Tanzanie", dialCode: "+255" },
  { code: "TG", name: "Togo", dialCode: "+228" },
  { code: "TN", name: "Tunisie", dialCode: "+216" },
  { code: "TR", name: "Turquie", dialCode: "+90" },
  { code: "UA", name: "Ukraine", dialCode: "+380" },
  { code: "VN", name: "Vietnam", dialCode: "+84" },
  { code: "YE", name: "Yemen", dialCode: "+967" },
  { code: "ZM", name: "Zambie", dialCode: "+260" },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263" },
];

export function getCountryFlag(countryCode: string) {
  return countryCode
    .toUpperCase()
    .replace(/./g, (character) =>
      String.fromCodePoint(127397 + character.charCodeAt(0)),
    );
}
