import type { Scholarship } from "@/lib/types";

const now = "2026-03-18T20:00:00.000Z";
const mandatoryDocuments = [
  "Carte Nationale d'identite",
  "Dernier diplome",
];

export const seedScholarships: Scholarship[] = [
  {
    id: "sch_eiffel",
    slug: "eiffel-excellence-france",
    title: "Programme Eiffel Excellence France",
    institution: "Ministere de l'Europe et des Affaires etrangeres",
    level: "Master / Doctorat",
    deadline: "2026-04-30",
    location: "Paris, Lyon, Lille",
    coverage: "Allocation mensuelle, billet d'avion, assurance et accompagnement d'installation",
    summary:
      "Voie d'excellence pour les profils internationaux a fort potentiel academique et strategique.",
    description:
      "Le programme Eiffel Excellence France finance des parcours de master et de doctorat dans les domaines prioritaires de l'Etat. La plateforme Vision France centralise les candidatures, la verification documentaire et la transmission aux etablissements partenaires afin d'accelerer l'instruction.",
    eligibility: [
      "Avoir un excellent dossier academique sur les trois dernieres annees",
      "Presenter un projet d'etudes coherent avec les priorites scientifiques ou economiques de la France",
      "Disposer d'un niveau de francais ou d'anglais compatible avec la formation visee",
    ],
    benefits: [
      "Prise en charge de l'installation et du voyage international",
      "Accompagnement administratif et orientation vers les etablissements",
      "Suivi de candidature avec notifications automatiques",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "12 a 36 mois",
    language: "Francais / Anglais",
    audience: "Etudiants internationaux a fort potentiel",
    seats: 45,
    institutionEmail: "eiffel@visionfrance.fr",
    featured: true,
    status: "open",
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_afrique",
    slug: "france-excellence-afrique",
    title: "France Excellence Afrique",
    institution: "Campus Vision France",
    level: "Licence / Master",
    deadline: "2026-05-15",
    location: "Paris, Montpellier, Toulouse",
    coverage: "Exoneration partielle, allocation de vie et tutorat d'integration",
    summary:
      "Programme cible pour accompagner les talents d'Afrique francophone vers des formations a forte employabilite.",
    description:
      "France Excellence Afrique renforce l'attractivite des filieres de sante, numerique, agriculture et politiques publiques. Les candidatures sont recues sur Vision France, verifiees par l'administration puis orientees vers les universites et ecoles qui poursuivent la selection finale.",
    eligibility: [
      "Etre titulaire d'un diplome ouvrant acces au niveau demande",
      "Resider hors de France au moment du depot de candidature",
      "Presenter un projet de retour ou d'impact professionnel dans son pays d'origine",
    ],
    benefits: [
      "Accompagnement visa et installation",
      "Suivi centralise des etapes administratives",
      "Mise en relation avec les etablissements partenaires",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "10 a 24 mois",
    language: "Francais",
    audience: "Talents d'Afrique francophone",
    seats: 120,
    institutionEmail: "afrique@visionfrance.fr",
    featured: true,
    status: "open",
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_green",
    slug: "innovation-verte-grenoble",
    title: "Bourse Innovation Verte Grenoble Alpes",
    institution: "Universite Grenoble Alpes",
    level: "Master",
    deadline: "2026-04-12",
    location: "Grenoble",
    coverage: "Exoneration de frais, bourse de recherche et mentorat laboratoire",
    summary:
      "Parcours destine aux candidats engages sur les transitions energetiques, montagne et climat.",
    description:
      "Ce dispositif met en relation les candidats internationaux avec les laboratoires et ecoles de l'Universite Grenoble Alpes. Vision France gere la reception des dossiers, la trace des statuts et la transmission aux responsables pedagogiques.",
    eligibility: [
      "Formation scientifique ou ingenierie avec resultats solides",
      "Projet de recherche ou d'innovation climat",
      "Experience ou engagement lie a la transition environnementale",
    ],
    benefits: [
      "Acces prioritaire aux laboratoires partenaires",
      "Coaching de dossier et suivi institutionnel",
      "Calendrier d'instruction transparent",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "24 mois",
    language: "Anglais / Francais",
    audience: "Etudiants en sciences et ingenierie",
    seats: 22,
    institutionEmail: "international@uga.example",
    featured: false,
    status: "closing",
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_numeric",
    slug: "francophonie-numerique-paris-saclay",
    title: "Francophonie Numerique Paris-Saclay",
    institution: "Universite Paris-Saclay",
    level: "Master / Doctorat",
    deadline: "2026-06-01",
    location: "Ile-de-France",
    coverage: "Bourse mensuelle, acces residence et appui innovation",
    summary:
      "Programme structure autour de l'IA, de la cybersecurite et de la gouvernance numerique.",
    description:
      "Paris-Saclay accueille des profils internationaux sur des parcours numeriques de pointe. Le guichet Vision France fluidifie les candidatures, trace chaque mise a jour et notifie les ecoles lorsque les dossiers peuvent entrer dans leur circuit interne.",
    eligibility: [
      "Dossier academique solide en informatique, mathematiques ou domaine connexe",
      "Projet professionnel oriente innovation ou transformation numerique",
      "Maitrise de l'anglais ou du francais selon le programme",
    ],
    benefits: [
      "Instruction centralisee et communication automatique",
      "Acces a des incubateurs et partenaires industriels",
      "Accompagnement pour les formalites d'arrivee",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "18 a 36 mois",
    language: "Anglais / Francais",
    audience: "Talents numeriques internationaux",
    seats: 34,
    institutionEmail: "admissions@universite-paris-saclay.example",
    featured: true,
    status: "open",
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_mer",
    slug: "sciences-de-la-mer-aix-marseille",
    title: "Sciences de la Mer Aix-Marseille",
    institution: "Aix-Marseille Universite",
    level: "Master",
    deadline: "2026-04-28",
    location: "Marseille",
    coverage: "Bourse de vie, soutien mobilite et immersion recherche",
    summary:
      "Offre orientee oceanographie, littoral, biodiversite marine et politiques de conservation.",
    description:
      "Cette bourse cible les candidats disposant d'un projet fort en sciences marines et adaptation des littoraux. L'instruction est geree via Vision France afin d'assurer une visibilite partagee entre l'administration, les universites et les candidats.",
    eligibility: [
      "Licence scientifique compatible",
      "Projet en lien avec environnement marin ou littoral",
      "Dossier motive et references academiques",
    ],
    benefits: [
      "Acces aux plateformes d'observation marine",
      "Suivi du dossier jusqu'a la transmission aux responsables",
      "Communication email a chaque changement de statut",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "24 mois",
    language: "Francais / Anglais",
    audience: "Etudiants sciences naturelles et environnement",
    seats: 18,
    institutionEmail: "international@univ-amu.example",
    featured: false,
    status: "open",
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_health",
    slug: "sante-globale-strasbourg",
    title: "Sante Globale Strasbourg",
    institution: "Universite de Strasbourg",
    level: "Master",
    deadline: "2026-03-31",
    location: "Strasbourg",
    coverage: "Prise en charge partielle, allocation de terrain et tutorat hospitalier",
    summary:
      "Parcours sante publique et cooperation sanitaire pour profils engages sur les enjeux globaux.",
    description:
      "La bourse Sante Globale accompagne des etudiants souhaitant travailler sur la prevention, la sante publique et la cooperation medicale. Vision France centralise le depot, l'examen administratif et la transmission a l'universite pour les etapes ulterieures.",
    eligibility: [
      "Formation prealable en sante, biologie, sciences sociales ou domaine connexe",
      "Interet demontre pour la sante publique internationale",
      "Capacite a suivre des enseignements en francais",
    ],
    benefits: [
      "Pilotage administratif unique",
      "Visibilite complete sur l'avancement de la candidature",
      "Relation continue avec l'etablissement d'accueil",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "18 mois",
    language: "Francais",
    audience: "Etudiants en sante et politiques publiques",
    seats: 16,
    institutionEmail: "sante-globale@unistra.example",
    featured: false,
    status: "closing",
    publishedAt: now,
    updatedAt: now,
  },
];
