import type { Scholarship } from "@/lib/types";

const now = "2026-03-19T08:00:00.000Z";
const verifiedAt = "2026-03-19";
const mandatoryDocuments = [
  "Carte nationale d'identité ou passeport",
  "Dernier diplôme ou attestation de niveau",
];

export const seedScholarships: Scholarship[] = [
  {
    id: "sch_paris_saclay_masters",
    slug: "universite-paris-saclay-international-masters-scholarships-program",
    title: "Université Paris-Saclay International Master's Scholarships Program",
    institution: "Université Paris-Saclay",
    level: "Master",
    deadline: "2026-03-31",
    deadlineLabel: "31 mars 2026 à 23 h 59 (heure de Paris)",
    location: "Île-de-France",
    coverage: "10 000 € par an + jusqu'à 1 000 € de frais de voyage ou de visa",
    summary:
      "Bourse d'excellence destinée aux étudiantes et étudiants internationaux admis dans un master de l'Université Paris-Saclay.",
    description:
      "Le programme international de bourses de master de l'Université Paris-Saclay accompagne les profils académiques à fort potentiel admis dans les formations de master de ses composantes. Les candidatures sont d'abord identifiées par les responsables de master, puis finalisées sur la plateforme de l'université avec lettre de recommandation.",
    eligibility: [
      "Être sélectionné par un responsable de master de l'Université Paris-Saclay avant le dépôt final",
      "Présenter un excellent dossier académique et un projet cohérent avec la formation visée",
      "Candidater en tant qu'étudiante ou étudiant international, avec un projet de poursuite d'études en France",
    ],
    benefits: [
      "Allocation de 10 000 € par an",
      "Jusqu'à 1 000 € supplémentaires pour les frais de voyage et de visa selon la situation",
      "Résultats annoncés à la mi-mai 2026",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "1 ou 2 années de master selon le programme",
    language: "Français / Anglais",
    audience: "Étudiantes et étudiants internationaux de master",
    seats: 0,
    institutionEmail: "paris-saclay@visionfrance.fr",
    featured: true,
    status: "closing",
    officialSource: "Université Paris-Saclay",
    officialUrl:
      "https://www.universite-paris-saclay.fr/en/admission/bourses-et-aides-financieres/international-masters-scholarships-program",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_grenoble_idex",
    slug: "universite-grenoble-alpes-idex-master-scholarships-2026-2027",
    title: "IdEx Master Scholarships 2026-2027",
    institution: "Université Grenoble Alpes",
    level: "Master / Diplôme d'ingénieur",
    deadline: "2026-05-31",
    deadlineLabel: "Calendrier variable selon le master ou le diplôme d'ingénieur visé",
    location: "Grenoble",
    coverage: "9 000 € en M1 ou Ingé 2A, 5 500 € en M2 ou Ingé 3A",
    summary:
      "Programme IdEx pour candidates et candidats internationaux admis dans une formation éligible de l'Université Grenoble Alpes.",
    description:
      "L'Université Grenoble Alpes publie pour 2026-2027 son programme de bourses IdEx à destination des étudiantes et étudiants internationaux postulant à certaines formations de master ou d'ingénieur. Les calendriers d'examen varient selon la composante et la décision finale est transmise après les comités d'admission.",
    eligibility: [
      "Être inscrit dans un établissement hors de France ou avoir obtenu son dernier diplôme à l'étranger",
      "Postuler à une formation UGA éligible pour l'année 2026-2027",
      "Présenter un excellent dossier académique examiné par la composante d'accueil",
    ],
    benefits: [
      "Versement en deux temps : mi-octobre 2026 puis février 2027",
      "Bourse attribuée pour une année universitaire",
      "Possibilité de redemander un soutien pour la seconde année du cursus",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "1 année universitaire renouvelable sur nouvelle sélection",
    language: "Français / Anglais selon la formation",
    audience: "Étudiantes et étudiants internationaux de master et d'ingénierie",
    seats: 0,
    institutionEmail: "uga-idex@visionfrance.fr",
    featured: true,
    status: "open",
    officialSource: "Université Grenoble Alpes",
    officialUrl:
      "https://www.univ-grenoble-alpes.fr/call-for-applications-idex-master-scholarships-2026-2027-academic-year-1545508.kjsp",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_lille_fellowships",
    slug: "universite-lille-graduate-programmes-fellowships-2026",
    title: "Graduate Programmes Fellowships 2026",
    institution: "Université de Lille",
    level: "Master",
    deadline: "2026-04-30",
    deadlineLabel: "Deux appels : du 15 février au 15 mars 2026 puis du 1er au 30 avril 2026",
    location: "Lille",
    coverage: "8 500 € pour les primo-arrivants, 4 500 € pour les autres profils éligibles",
    summary:
      "Bourses d'excellence pour intégrer l'un des Graduate Programmes de l'Université de Lille à la rentrée 2026.",
    description:
      "Les Graduate Programmes de l'Université de Lille ouvrent en 2026 deux vagues de candidature pour financer l'accès à leurs parcours de master. Le premier appel est clos et le second ouvre le 1er avril 2026, avec des bourses différenciées selon qu'il s'agit d'une première arrivée en France ou d'une poursuite d'études.",
    eligibility: [
      "Candidater à un master rattaché à l'un des Graduate Programmes de l'Université de Lille",
      "Présenter un projet académique ou de recherche cohérent avec le Graduate Programme visé",
      "Justifier d'excellents résultats académiques et, le cas échéant, d'un statut de primo-arrivant en France",
    ],
    benefits: [
      "Versement en dix mensualités à partir d'octobre",
      "Renouvellement possible pour la deuxième année sur nouvelle demande",
      "Résultats du second appel annoncés le 29 mai 2026",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "1 année universitaire renouvelable",
    language: "Français / Anglais selon le programme",
    audience: "Étudiantes et étudiants internationaux de master",
    seats: 0,
    institutionEmail: "lille-graduate@visionfrance.fr",
    featured: true,
    status: "upcoming",
    officialSource: "Université de Lille",
    officialUrl: "https://graduate-programmes.univ-lille.fr/en/fellowships",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_amu_tiger_ai4ph",
    slug: "aix-marseille-universite-tiger-ai4ph",
    title: "TIGER Excellence Scholarship for Incoming Mobility in M2 AI4PH",
    institution: "Aix-Marseille Université",
    level: "Master 2",
    deadline: "2026-05-11",
    deadlineLabel: "11 mai 2026 à 12 h (heure de France)",
    location: "Marseille",
    coverage: "10 000 € sur un an + accompagnement à l'installation + logement sous conditions",
    summary:
      "Bourse d'excellence pour le parcours AI4PH du master de santé publique d'Aix-Marseille Université.",
    description:
      "Le dispositif TIGER du parcours Artificial Intelligence for Public Health finance des étudiantes et étudiants internationaux souhaitant rejoindre à Marseille le M2 AI4PH. Les dossiers conformes sont examinés, puis les profils présélectionnés sont convoqués à un entretien oral prévu le 19 mai 2026.",
    eligibility: [
      "Être étudiante ou étudiant international non français et n'avoir jamais été inscrit dans un établissement français",
      "Présenter d'excellents résultats académiques dans un cursus pertinent pour la santé publique ou l'IA",
      "S'inscrire dans la spécialisation M2 AI4PH en mobilité présentielle",
    ],
    benefits: [
      "Financement jusqu'à 10 000 € pour l'année universitaire",
      "Service personnalisé d'accueil et d'installation en France",
      "Entretien de sélection pour les candidates et candidats présélectionnés",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "1 année universitaire",
    language: "Anglais",
    audience: "Étudiantes et étudiants internationaux en santé publique, data et IA",
    seats: 0,
    institutionEmail: "amu-ai4ph@visionfrance.fr",
    featured: true,
    status: "open",
    officialSource: "Aix-Marseille Université - SESSTIM",
    officialUrl: "https://sesstim.univ-amu.fr/en/tiger-scholarship-incoming-mobility-ai4ph",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_gi_eif_2026",
    slug: "universite-claude-bernard-lyon-1-gi-eif-excellence-scholarships-2026",
    title: "GI EIF Excellence Scholarships 2026",
    institution: "Université Claude Bernard Lyon 1",
    level: "Master 2",
    deadline: "2026-03-30",
    deadlineLabel: "30 mars 2026 pour la thématique encore ouverte",
    location: "Lyon",
    coverage: "1 000 € par mois pendant 10 mois + exonération des frais d'inscription",
    summary:
      "Campagne 2026 de la Graduate Initiative Energy and Industry of the Future pour des masters d'ingénierie à Lyon 1.",
    description:
      "Le programme GI EIF de l'Université Claude Bernard Lyon 1 finance des étudiantes et étudiants internationaux de master 2 en ingénierie souhaitant mener un stage de recherche en laboratoire. Au 19 mars 2026, trois thématiques sont closes et une dernière thématique reste ouverte jusqu'au 30 mars 2026.",
    eligibility: [
      "Être un nouvel étudiant international vivant hors de France au moment de la candidature",
      "Avoir validé un niveau M1 dans un domaine pertinent de l'ingénierie avant le 1er septembre 2026",
      "Présenter un projet professionnel cohérent avec la thématique et le laboratoire d'accueil",
    ],
    benefits: [
      "10 000 € de bourse sur dix mois",
      "Frais d'inscription de master pris en charge",
      "Stage de recherche intégré dans un laboratoire de Lyon 1",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "1 année de master 2",
    language: "Anglais / Français selon la filière",
    audience: "Étudiantes et étudiants internationaux en ingénierie",
    seats: 4,
    institutionEmail: "lyon1-eif@visionfrance.fr",
    featured: false,
    status: "closing",
    officialSource: "Université Claude Bernard Lyon 1 - GI EIF",
    officialUrl: "https://gi-eif.univ-lyon1.fr/scholarships.html",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_idil_montpellier",
    slug: "universite-montpellier-idil-international-scholarships",
    title: "IDIL International Scholarships",
    institution: "Université de Montpellier",
    level: "Master",
    deadline: "2026-06-30",
    deadlineLabel: "Calendrier variable selon le parcours IDIL et la procédure Études en France",
    location: "Montpellier",
    coverage: "4 mois à 600 €/mois + jusqu'à 600 € de transport + stage financé",
    summary:
      "Dispositif d'accueil pour les étudiantes et étudiants internationaux intégrant un parcours IDIL à Montpellier.",
    description:
      "Le programme gradué IDIL de l'Université de Montpellier propose des aides dédiées aux étudiantes et étudiants internationaux qui rejoignent un parcours IDIL et n'ont pas étudié dans l'enseignement supérieur français durant les deux dernières années. Les cursus sont dispensés en anglais et combinent immersion en laboratoire, stage financé et appui à l'arrivée en France.",
    eligibility: [
      "Postuler à un parcours IDIL de l'Université de Montpellier",
      "Ne pas avoir étudié dans un établissement d'enseignement supérieur français durant les deux dernières années",
      "Être en mesure de suivre un parcours enseigné en anglais",
    ],
    benefits: [
      "Bourse IDIL de 600 € par mois sur quatre mois en M1 et M2",
      "Prise en charge du transport jusqu'à 600 €",
      "Cours de français langue étrangère et découverte culturelle",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "Master 1 et Master 2",
    language: "Anglais",
    audience: "Étudiantes et étudiants internationaux de master",
    seats: 0,
    institutionEmail: "montpellier-idil@visionfrance.fr",
    featured: false,
    status: "open",
    officialSource: "Université de Montpellier - IDIL Graduate Program",
    officialUrl:
      "https://idil.edu.umontpellier.fr/en/accueil-des-etudiants-internationaux-2/la-prise-en-charge-idil/",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_ens_psl_selection",
    slug: "ens-psl-international-selection-2026",
    title: "ENS-PSL International Selection 2026",
    institution: "École normale supérieure - PSL",
    level: "Licence 3 / Master 1",
    deadline: "2025-12-15",
    deadlineLabel:
      "Session 2026 close le 3 décembre 2025 en lettres et le 15 décembre 2025 en sciences",
    location: "Paris",
    coverage: "1 000 € par mois pendant 3 ans + chambre sur un campus ENS",
    summary:
      "Concours international de l'ENS-PSL pour recruter des étudiantes et étudiants internationaux d'excellence.",
    description:
      "L'International Selection de l'ENS-PSL permet l'admission d'étudiantes et d'étudiants internationaux en troisième année de licence ou en première année de master. La session 2026 propose dix places en sciences et dix places en arts et humanités, avec bourse mensuelle et hébergement sur campus.",
    eligibility: [
      "Justifier d'au moins une année d'études universitaires obtenue hors de France avant la candidature",
      "Ne pas avoir déjà candidaté à l'International Selection",
      "Ne pas avoir vécu en France plus de dix mois sur l'année universitaire en cours et la précédente",
    ],
    benefits: [
      "20 places ouvertes au total pour la session 2026",
      "Bourse de 1 000 € par mois pendant 3 ans",
      "Chambre sur un campus ENS et accompagnement visa à l'admission",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "3 années",
    language: "Français / Anglais selon la discipline",
    audience: "Jeunes diplômées et diplômés internationaux d'excellence",
    seats: 20,
    institutionEmail: "ens-psl@visionfrance.fr",
    featured: false,
    status: "closed",
    officialSource: "ENS-PSL",
    officialUrl:
      "https://www.ens.psl.eu/en/une-formation-d-exception/admissions/international/international-selection",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_boutmy_2026",
    slug: "sciences-po-emile-boutmy-scholarship-2026",
    title: "Émile Boutmy Scholarship",
    institution: "Sciences Po",
    level: "Bachelor / Master",
    deadline: "2026-01-20",
    deadlineLabel:
      "Master : 19 octobre 2025 ou 30 novembre 2025 ; bachelor : 20 janvier 2026",
    location: "Paris",
    coverage: "Jusqu'à 9 500 € d'exonération en bachelor ou 18 500 € par an en master",
    summary:
      "Bourse d'accueil de Sciences Po pour les meilleurs profils internationaux hors Union européenne.",
    description:
      "La bourse Émile Boutmy de Sciences Po vise les étudiantes et étudiants non européens admis pour la première fois à Sciences Po en bachelor ou en master. Elle prend la forme d'une exonération totale ou partielle des droits de scolarité, accordée sur critères de mérite et de profil.",
    eligibility: [
      "Être primo-candidat à Sciences Po et ressortissant d'un État hors Union européenne",
      "Ne pas être fiscalement rattaché à un foyer imposé dans l'Union européenne",
      "Être admis dans un programme éligible de bachelor ou de master",
    ],
    benefits: [
      "Exonération jusqu'à 9 500 € en bachelor",
      "Exonération de 18 500 € par an en master",
      "Renouvellement possible selon la progression académique et le parcours choisi",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "1 à 2 années selon le cursus",
    language: "Français / Anglais selon le programme",
    audience: "Étudiantes et étudiants internationaux hors Union européenne",
    seats: 0,
    institutionEmail: "sciencespo@visionfrance.fr",
    featured: false,
    status: "closed",
    officialSource: "Sciences Po",
    officialUrl:
      "https://www.sciencespo.fr/students/en/fees-funding/financial-aid/emile-boutmy-scholarship",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_eiffel_paris_saclay",
    slug: "universite-paris-saclay-france-excellence-eiffel-2026",
    title: "France Excellence Eiffel via Université Paris-Saclay",
    institution: "Université Paris-Saclay",
    level: "Master / Doctorat",
    deadline: "2025-11-09",
    deadlineLabel:
      "Campagne 2026-2027 close le 9 novembre 2025 à Paris-Saclay ; résultats Campus France ensuite",
    location: "Île-de-France",
    coverage: "1 200 € par mois en master ou 2 100 € par mois en doctorat, en plus de services directs",
    summary:
      "Déclinaison Paris-Saclay du programme France Excellence Eiffel pour les profils internationaux de haut niveau.",
    description:
      "L'Université Paris-Saclay accepte, accompagne et soumet à Campus France les candidatures Eiffel pour ses formations de master et de doctorat. L'appel 2026-2027 a été ouvert du 1er octobre au 9 novembre 2025 avec dépôt institutionnel avant examen final par Campus France.",
    eligibility: [
      "Candidater à une formation Paris-Saclay éligible en master ou doctorat",
      "Respecter les critères d'âge et de domaine d'études fixés par le programme Eiffel",
      "Ne pas cumuler cette aide avec une autre bourse du gouvernement français",
    ],
    benefits: [
      "1 200 € par mois au niveau master",
      "2 100 € par mois au niveau doctorat",
      "Appui institutionnel de Paris-Saclay avant transmission à Campus France",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "12 à 36 mois selon le niveau",
    language: "Français / Anglais",
    audience: "Étudiantes et étudiants internationaux de haut niveau",
    seats: 0,
    institutionEmail: "paris-saclay-eiffel@visionfrance.fr",
    featured: true,
    status: "closed",
    officialSource: "Université Paris-Saclay",
    officialUrl:
      "https://www.universite-paris-saclay.fr/en/admission/bourses-et-aides-financieres/eiffel-scholarship-programme",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_paris_saclay_phd_track",
    slug: "universite-paris-saclay-phd-track-2026",
    title: "PhD Track Support Programme for Doctoral Studies",
    institution: "Université Paris-Saclay",
    level: "Master 1 / Master 2 vers doctorat",
    deadline: "2026-03-05",
    deadlineLabel: "5 mars 2026 à 11 h (heure de Paris)",
    location: "Île-de-France",
    coverage: "10 bourses en 2026 + mentorat, financement de master et contrat doctoral sous conditions",
    summary:
      "Parcours structuré vers le doctorat pour étudiantes et étudiants intéressés par la recherche à l'Université Paris-Saclay.",
    description:
      "Le PhD Track de l'Université Paris-Saclay associe mentorat, parcours d'accompagnement, bourse de master puis contrat doctoral au sein d'un laboratoire de l'université. Pour la session 2026, dix bourses étaient annoncées, dont quatre fléchées développement durable.",
    eligibility: [
      "Être en M1 à l'Université Paris-Saclay ou dans un profil admis dans un M2 pertinent via une Graduate School",
      "Porter un projet de recherche cohérent avec une équipe d'accueil et une future poursuite en doctorat",
      "Déposer un dossier complet incluant CV, projet, relevés et recommandation",
    ],
    benefits: [
      "10 bourses annoncées pour la session 2026",
      "Mentorat par un enseignant-chercheur ou un chercheur",
      "Poursuite possible en doctorat sous réserve d'avis favorable de l'école doctorale",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "2 années de master + 3 années de doctorat sous conditions",
    language: "Français / Anglais",
    audience: "Étudiantes et étudiants visant une trajectoire de recherche doctorale",
    seats: 10,
    institutionEmail: "paris-saclay-phdtrack@visionfrance.fr",
    featured: false,
    status: "closed",
    officialSource: "Université Paris-Saclay",
    officialUrl:
      "https://www.universite-paris-saclay.fr/en/phd-track-support-programme-doctoral-studies",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_adi_cotutelle",
    slug: "universite-paris-saclay-adi-cotutelle-2026",
    title: "ADI International Doctoral Cotutelle Funding Programme 2026",
    institution: "Université Paris-Saclay",
    level: "Doctorat",
    deadline: "2026-02-22",
    deadlineLabel: "22 février 2026 pour le dépôt des sujets sur la plateforme ADUM",
    location: "Île-de-France / cotutelle internationale",
    coverage: "Financement doctoral en cotutelle internationale avec établissement partenaire",
    summary:
      "Programme de financement pour des thèses en cotutelle internationale associant Paris-Saclay et une université étrangère.",
    description:
      "Le programme ADI soutient les doctorats réalisés en cotutelle entre l'Université Paris-Saclay et un établissement partenaire à l'étranger. Les unités de recherche françaises doivent appartenir à Paris-Saclay et les sujets sont déposés sur ADUM dans le calendrier annuel prévu.",
    eligibility: [
      "Préparer une thèse en cotutelle avec une institution partenaire à l'étranger",
      "Être admissible dans une école doctorale de l'Université Paris-Saclay",
      "S'appuyer sur une unité de recherche française rattachée à Paris-Saclay",
    ],
    benefits: [
      "Dispositif dédié aux cotutelles doctorales internationales",
      "Instruction centralisée via les écoles doctorales et ADUM",
      "Coordination académique entre les deux établissements partenaires",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "Doctorat en cotutelle",
    language: "Français / Anglais",
    audience: "Doctorantes et doctorants en cotutelle internationale",
    seats: 0,
    institutionEmail: "paris-saclay-adi@visionfrance.fr",
    featured: false,
    status: "closed",
    officialSource: "Université Paris-Saclay",
    officialUrl:
      "https://www.universite-paris-saclay.fr/en/adi-international-doctoral-cotutelle-funding-programme-2025",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_light_in_paris",
    slug: "light-in-paris-phd-fellowship-2026",
    title: "Light in Paris PhD Fellowship Programme",
    institution: "Université Paris-Saclay",
    level: "Doctorat",
    deadline: "2026-02-23",
    deadlineLabel: "23 février 2026 à 23 h 59 (heure de Paris)",
    location: "Paris-Saclay",
    coverage: "30 contrats doctoraux financés dans les sciences de la lumière",
    summary:
      "Programme doctoral international centré sur les sciences de la lumière et les projets interdisciplinaires de recherche.",
    description:
      "Le programme Light in Paris finance des doctorantes et doctorants sur des sujets liés aux sciences de la lumière au sein de l'écosystème Paris-Saclay. Le dispositif est soutenu par Horizon Europe, l'Université Paris-Saclay et des partenaires industriels, avec trente postes doctoraux annoncés.",
    eligibility: [
      "Candidater à un sujet doctoral proposé dans le cadre du programme Light in Paris",
      "Être en capacité de rejoindre un laboratoire hôte de l'Université Paris-Saclay",
      "Présenter un profil compatible avec un projet de recherche international et intersectoriel",
    ],
    benefits: [
      "30 contrats doctoraux financés",
      "Programme international et interdisciplinaire en sciences de la lumière",
      "Adossement à des laboratoires Paris-Saclay et à des partenaires industriels",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "Doctorat",
    language: "Anglais",
    audience: "Doctorantes et doctorants internationaux en photonique et sciences de la lumière",
    seats: 30,
    institutionEmail: "paris-saclay-light@visionfrance.fr",
    featured: false,
    status: "closed",
    officialSource: "Institut des Sciences Moléculaires d'Orsay - Université Paris-Saclay",
    officialUrl:
      "https://www.ismo.universite-paris-saclay.fr/en/apply-for-a-phd-fellowship-from-the-light-in-paris-programme/",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
  {
    id: "sch_neurograduate",
    slug: "neurograduate-lyon-1-fully-funded-scholarships-2026",
    title: "NeuroGraduate Fully Funded Scholarships 2026",
    institution: "Université Claude Bernard Lyon 1",
    level: "Master 1 / Master 2",
    deadline: "2026-01-23",
    deadlineLabel: "23 janvier 2026 pour les bourses master 1 ouvertes à l'international",
    location: "Lyon",
    coverage: "1 000 € par mois pendant 10 mois",
    summary:
      "Bourses entièrement financées pour intégrer les parcours neurosciences de Lyon 1.",
    description:
      "La NeuroGraduate School de l'Université Claude Bernard Lyon 1 annonçait pour 2025-2026 cinq bourses intégralement financées d'un an pour des étudiantes et étudiants étrangers souhaitant rejoindre ses parcours de neurosciences. Le site mentionne également d'autres aides de mobilité et d'internat selon les niveaux et parcours.",
    eligibility: [
      "Être un étudiant international candidatant à un parcours de neurosciences de Lyon 1",
      "Présenter un excellent niveau académique dans un champ compatible avec les neurosciences",
      "Respecter le calendrier et les consignes de l'appel dédié",
    ],
    benefits: [
      "5 bourses d'un an annoncées pour les parcours master",
      "Financement de 1 000 € par mois pendant 10 mois",
      "Intégration à une graduate school fortement internationalisée",
    ],
    requiredDocuments: mandatoryDocuments,
    duration: "1 année universitaire",
    language: "Anglais",
    audience: "Étudiantes et étudiants internationaux en neurosciences",
    seats: 5,
    institutionEmail: "lyon1-neuro@visionfrance.fr",
    featured: false,
    status: "closed",
    officialSource: "NeuroGraduate School - Université Claude Bernard Lyon 1",
    officialUrl: "https://neurograduate.univ-lyon1.fr/fellowships/",
    verifiedAt,
    publishedAt: now,
    updatedAt: now,
  },
];
